### ISSUE TITLE
How to change date format?

### ISSUE THREAD

**Issue by 1a57danc3** [JeremyFan/hexo-theme-still#2]
_config.yaml in my hexo root folder.
```
date_format: DD-MM-YYYY
time_format: HH:mm:ss
```

but `item.date` in this theme is `May 1, 2018`

**Comment by JeremyFan** [comment]
The previous date is not associated with the `_config.yml`

fixed. see this [commit](https://github.com/JeremyFan/hexo-theme-still/commit/bb3dc674abd87f4f2480f074a8e8e863be7f48c7)

**Comment by 1a57danc3** [comment]
Thx!
